### ISSUE TITLE
emc_vipr_driver_common.py (__init__): volume_backend_name always set to DEFAULT

### ISSUE THREAD

**Issue by strus38** [emcvipr/controller-openstack-cinder#5]
The volume_backend_name is always set to DEFAULT when using enabled_backends and never read in the cinder.conf file.
Example:
enabled_backends=powervc,emc-vmax,EMCViPRFCDriver
...
[EMCViPRFCDriver]
volume_driver=cinder.volume.drivers.emc.vipr.emc_vipr_fc.EMCViPRFCDriver
volume_backend_name=EMCViPRFCDriver
vipr_hostname=vipr-client-210.<domain>
vipr_port=4443
vipr_username=root
vipr_password=cloud123
vipr_tenant=Provider Tenant
vipr_project=TestProject
vipr_varray=VMAX40K_VA
vipr_cookiedir=/usr/cookie
vipr_storage_vmax=True

The value of self.configuration.volume_backend_name is DEFAULT.

This prevents creating a new volume using cinder.
Workaround: force the value in emc_vipr_driver_common.py.

**Comment by parash-hallur** [comment]
This issue is not reproducible, hence closing it.
